# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 60845c5c5feb14d694b4700c390fca2b1d8b93eb6a123579a114352724fc722a4083ed2c38264af3bdcef53e24b52a91c37117d9fa975be0be2d54bf0d8e97c0

test:
  secret_key_base: 176f841844d89f388faed4f913a83837efa0550662e9c40cbe69c723a47b9c37add9f77461730056a4d3f7930c19205417bcdcf3620639c6b467b2630fbe7f36

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
